package errors

func HandleError(err error) {
	panic(err)
}